spring:
  datasource:
    url: jdbc:mysql://localhost:3307/uams?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: hzy2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

dfs:
  storage:
    type: minio
    minio:
      endpoint: http://127.0.0.1:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket: uams-files

ai:
  deepseek:
    api-key: sk-05810d439bd9409ca01e64d0ac2ddf14
    endpoint: https://api.deepseek.com/chat/completions
